apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::767397811804:user/admin23i-1
      username: admin23i-1
      groups:
        - system:masters
